security:
  user:
    password: password


server:
  port: 9999
  contextPath: /uaa

info:
  version: 1.0
  name: Spring APP Auth
  api: /uaa
  profile: default

logging:
  level:
    org.springframework.security: DEBUG
